"""Initial migration

Revision ID: 721c2465cef9
Revises: 
Create Date: 2024-10-20 00:00:58.369436

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '721c2465cef9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('missao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome_missao', sa.String(length=50), nullable=False),
    sa.Column('data_lancamento', sa.Date(), nullable=False),
    sa.Column('destino', sa.String(length=30), nullable=False),
    sa.Column('estado_missao', sa.String(length=30), nullable=False),
    sa.Column('tripulacao', sa.String(length=60), nullable=False),
    sa.Column('carga_util', sa.String(length=60), nullable=False),
    sa.Column('duracao_missao', sa.String(length=30), nullable=False),
    sa.Column('custo_missao', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('status_missao', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('missao')
    # ### end Alembic commands ###
